library (readr)
urlfile="https://raw.githubusercontent.com/ryanmar814/datavizfinal/master/books_publisher.csv"
books_publisher <- read_csv(url(urlfile))
head(books_publisher)
urlfile="https://raw.githubusercontent.com/ryanmar814/datavizfinal/master/top100.csv"
top100 <- read_csv(url(urlfile))
view(top100)
library(tidyverse)
toppub <- select(top100, 1:12)
view(toppub)
library(dplyr)
pub <- group_by(toppub, publisher)
view(pub)
pubs <- arrange(pub, publisher)
view(pubs)
pubs2 <- pubs %>% count(publisher, sort = TRUE)
pubs2
install.packages("wordcloud")
library(wordcloud)
install.packages("RColorBrewer")
install.packages("SnowballC")
install.packages("tm")
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
wordcloud(words = pubs2$publisher, freq = pubs2$n, min.freq = 2, colors=brewer.pal(8, "Dark2"))
